import React, { forwardRef } from 'react';
import { useAuth } from '../../hooks/useAuth';
import { useTranslation } from 'react-i18next';

interface ReportProps {
  data: any[]; 
  totalRevenue: number;
  period: string;
}

export const FinancialReport = forwardRef<HTMLDivElement, ReportProps>((props, ref) => {
  const { user } = useAuth();
  const { i18n } = useTranslation();

  // O "Interruptor" Inteligente
  const isEN = i18n.language === 'en';
  const locale = isEN ? 'en-US' : 'pt-BR';
  const currencyCode = isEN ? 'USD' : 'BRL';

  const date = new Date().toLocaleDateString(locale);

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat(locale, { style: 'currency', currency: currencyCode }).format(value);
  };

  return (
    <div ref={ref} className="p-10 bg-white text-black font-sans w-full">
      
      {/* Cabeçalho do Relatório */}
      <div className="flex justify-between items-center border-b-2 border-gray-800 pb-4 mb-8">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">
            {isEN ? 'Financial Report' : 'Relatório Financeiro'}
          </h1>
          <p className="text-sm text-gray-600">
            {isEN ? 'Generated via Cleverya App' : 'Gerado via Cleverya App'}
          </p>
        </div>
        <div className="text-right">
          <h2 className="text-xl font-bold">{user?.user_metadata?.business_name || (isEN ? 'My Business' : 'Minha Empresa')}</h2>
          <p className="text-sm text-gray-500">{isEN ? 'Date' : 'Data'}: {date}</p>
          <p className="text-sm text-gray-500">{isEN ? 'Period' : 'Período'}: {props.period}</p>
        </div>
      </div>

      {/* Resumo */}
      <div className="mb-8 p-4 bg-gray-100 rounded-lg border border-gray-300">
        <h3 className="text-lg font-bold mb-2">{isEN ? 'Period Summary' : 'Resumo do Período'}</h3>
        <div className="text-4xl font-bold text-green-700">
          {formatCurrency(props.totalRevenue)}
        </div>
        <p className="text-sm text-gray-600">{isEN ? 'Total Confirmed Revenue' : 'Faturamento Total Confirmado'}</p>
      </div>

      {/* Tabela de Dados */}
      <table className="w-full text-left border-collapse">
        <thead>
          <tr className="border-b border-gray-400">
            <th className="py-2 font-bold">{isEN ? 'Date' : 'Data'}</th>
            <th className="py-2 font-bold">{isEN ? 'Customer' : 'Cliente'}</th>
            <th className="py-2 font-bold">{isEN ? 'Service' : 'Serviço'}</th>
            <th className="py-2 font-bold text-right">{isEN ? 'Value' : 'Valor'}</th>
          </tr>
        </thead>
        <tbody>
          {props.data.map((item, index) => (
            <tr key={index} className="border-b border-gray-200">
              <td className="py-2">{new Date(item.start_time).toLocaleDateString(locale)}</td>
              <td className="py-2">{item.client_name}</td>
              <td className="py-2">{item.service_name}</td>
              <td className="py-2 text-right">
                {formatCurrency(item.price)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Rodapé */}
      <div className="mt-12 pt-4 border-t border-gray-300 text-center text-xs text-gray-500">
        <p>{isEN ? 'Document automatically generated by the Cleverya platform.' : 'Documento gerado automaticamente pela plataforma Cleverya.'}</p>
        <p>www.cleverya.com</p>
      </div>
    </div>
  );
});

FinancialReport.displayName = 'FinancialReport';